// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import path from "path";

// Get the project root (two levels up from src/lib)
const projectRoot = path.resolve(__dirname, "../..");

export default defineConfig({
  schema: path.join(projectRoot, "prisma/schema.prisma"),
  migrations: {
    path: path.join(projectRoot, "prisma/migrations"),
    seed: "node prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
